name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./mvnw clean assembly:single

      - name: Get version
        id: get-version
        run: |
          VERSION=$( ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout )
          FINAL_NAME=$( ./mvnw help:evaluate -Dexpression=project.build.finalName -q -DforceStdout )
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=final-name::$FINAL_NAME"
      
      - name: Display version
        id: display-version
        run: |
          echo "version: ${{ steps.get-version.outputs.version }}"
          echo "final_name: ${{ steps.get-version.outputs.final-name }}"

      - name: Rename .zip to .bos
        run: |
          cp target/${{ steps.get-version.outputs.final-name }}.zip target/${{ steps.get-version.outputs.final-name }}.bos
          ls -ltr target

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get-version.outputs.final-name }}.bos
          path: target/${{ steps.get-version.outputs.final-name }}.bos
    
